(() => {
    const english = {
        "nav.home": "Home", "nav.support": "Support", "nav.privacy": "Privacy",
        "home.eyebrow": "Ivory Note 1.1",
        "home.title": "Record what matters. Keep it yours.",
        "home.lede": "Ivory Note recognizes the language you speak, creates a clear transcript, and builds useful study material while keeping your content on your device.",
        "home.support": "Get support", "home.policy": "Read the privacy policy",
        "home.see": "See Ivory Note", "home.workspace": "Capture, transcribe, and review in one quiet workspace.",
        "home.caption.notes": "Organized notes", "home.caption.record": "One-tap recording",
        "home.caption.private": "Private by design", "home.caption.watch": "Apple Watch recording",
        "home.new": "New in 1.1", "home.featuresTitle": "Your language. The full context. Still private.",
        "home.feature.transcription.title": "Multilingual transcription",
        "home.feature.transcription.body": "Ivory Note automatically detects the spoken language and transcribes locally with its included speech model.",
        "home.feature.titles.title": "Context-aware titles",
        "home.feature.titles.body": "Long recordings are titled from their dominant subject instead of a greeting or the first few words.",
        "home.feature.languages.title": "Seven interface languages",
        "home.feature.languages.body": "Use Ivory Note in English, Spanish, French, German, Portuguese, Simplified Chinese, or Russian.",
        "home.privacy.eyebrow": "Privacy first", "home.privacy.title": "No account. No advertising. No cloud transcription.",
        "home.privacy.body": "Your notes and audio are stored locally. Ivory Note does not operate an account system or a server that receives your recordings. You control deletion from inside the app.",
        "home.privacy.link": "See the full policy",
        "support.eyebrow": "Ivory Note help", "support.lede": "Straightforward help for recording, transcription, storage, widgets, and Apple Watch.",
        "support.languages.title": "Which languages does Ivory Note support?",
        "support.languages.body": "Ivory Note 1.1 automatically detects the spoken language during on-device transcription. The app interface is available in English, Spanish, French, German, Portuguese, Simplified Chinese, and Russian.",
        "support.titles.title": "How does Ivory Note title a long recording?",
        "support.titles.body": "Ivory Note analyzes repeated subjects across the complete transcript and favors the dominant topic instead of the greeting or first sentence.",
        "support.contact": "Still need help?",
        "privacy.eyebrow": "Ivory Note legal", "privacy.title": "Privacy Policy",
        "privacy.lede": "Ivory Note is designed to keep your voice notes private and under your control.",
        "privacy.date": "Effective date: June 19, 2026"
    };

    const translations = {
        en: english,
        es: {
            "nav.home":"Inicio","nav.support":"Soporte","nav.privacy":"Privacidad","home.eyebrow":"Ivory Note 1.1","home.title":"Graba lo que importa. Mantenlo tuyo.","home.lede":"Ivory Note reconoce el idioma que hablas, crea una transcripción clara y genera material de estudio útil manteniendo tu contenido en el dispositivo.","home.support":"Obtener ayuda","home.policy":"Leer la política de privacidad","home.see":"Descubre Ivory Note","home.workspace":"Graba, transcribe y repasa en un espacio tranquilo.","home.caption.notes":"Notas organizadas","home.caption.record":"Grabación con un toque","home.caption.private":"Privacidad desde el diseño","home.caption.watch":"Grabación con Apple Watch","home.new":"Novedades de 1.1","home.featuresTitle":"Tu idioma. Todo el contexto. La misma privacidad.","home.feature.transcription.title":"Transcripción multilingüe","home.feature.transcription.body":"Ivory Note detecta automáticamente el idioma hablado y transcribe localmente con el modelo incluido.","home.feature.titles.title":"Títulos con contexto","home.feature.titles.body":"Las grabaciones largas se titulan según el tema principal, no según el saludo o las primeras palabras.","home.feature.languages.title":"Siete idiomas de interfaz","home.feature.languages.body":"Usa Ivory Note en inglés, español, francés, alemán, portugués, chino simplificado o ruso.","home.privacy.eyebrow":"Privacidad primero","home.privacy.title":"Sin cuenta. Sin anuncios. Sin transcripción en la nube.","home.privacy.body":"Tus notas y audios se guardan localmente. Ivory Note no utiliza un sistema de cuentas ni un servidor que reciba tus grabaciones. Tú controlas la eliminación desde la app.","home.privacy.link":"Ver la política completa","support.eyebrow":"Ayuda de Ivory Note","support.lede":"Ayuda sencilla para grabación, transcripción, almacenamiento, widgets y Apple Watch.","support.languages.title":"¿Qué idiomas admite Ivory Note?","support.languages.body":"Ivory Note 1.1 detecta automáticamente el idioma hablado durante la transcripción en el dispositivo. La interfaz está disponible en inglés, español, francés, alemán, portugués, chino simplificado y ruso.","support.titles.title":"¿Cómo titula Ivory Note una grabación larga?","support.titles.body":"Ivory Note analiza los temas repetidos en toda la transcripción y prioriza el tema dominante en lugar del saludo o la primera frase.","support.contact":"¿Aún necesitas ayuda?","privacy.eyebrow":"Información legal de Ivory Note","privacy.title":"Política de privacidad","privacy.lede":"Ivory Note está diseñado para mantener tus notas de voz privadas y bajo tu control.","privacy.date":"Fecha de entrada en vigor: 19 de junio de 2026"
        },
        fr: {
            "nav.home":"Accueil","nav.support":"Assistance","nav.privacy":"Confidentialité","home.eyebrow":"Ivory Note 1.1","home.title":"Enregistrez l’essentiel. Gardez-le pour vous.","home.lede":"Ivory Note reconnaît votre langue, crée une transcription claire et produit du matériel d’étude utile tout en gardant votre contenu sur l’appareil.","home.support":"Obtenir de l’aide","home.policy":"Lire la politique de confidentialité","home.see":"Découvrir Ivory Note","home.workspace":"Enregistrez, transcrivez et révisez dans un espace calme.","home.caption.notes":"Notes organisées","home.caption.record":"Enregistrement en un geste","home.caption.private":"Confidentiel par conception","home.caption.watch":"Enregistrement Apple Watch","home.new":"Nouveautés de la version 1.1","home.featuresTitle":"Votre langue. Tout le contexte. Toujours privé.","home.feature.transcription.title":"Transcription multilingue","home.feature.transcription.body":"Ivory Note détecte automatiquement la langue parlée et transcrit localement avec son modèle inclus.","home.feature.titles.title":"Titres contextuels","home.feature.titles.body":"Les longs enregistrements sont titrés selon leur sujet principal, pas selon les premières paroles.","home.feature.languages.title":"Sept langues d’interface","home.feature.languages.body":"Utilisez Ivory Note en anglais, espagnol, français, allemand, portugais, chinois simplifié ou russe.","home.privacy.eyebrow":"La confidentialité d’abord","home.privacy.title":"Aucun compte. Aucune publicité. Aucune transcription cloud.","home.privacy.body":"Vos notes et vos fichiers audio sont stockés localement. Ivory Note ne possède ni système de compte ni serveur recevant vos enregistrements. Vous contrôlez leur suppression dans l’app.","home.privacy.link":"Voir la politique complète","support.eyebrow":"Aide Ivory Note","support.lede":"Une aide claire pour l’enregistrement, la transcription, le stockage, les widgets et l’Apple Watch.","support.languages.title":"Quelles langues Ivory Note prend-il en charge ?","support.languages.body":"Ivory Note 1.1 détecte automatiquement la langue parlée pendant la transcription sur l’appareil. L’interface est disponible en anglais, espagnol, français, allemand, portugais, chinois simplifié et russe.","support.titles.title":"Comment Ivory Note titre-t-il un long enregistrement ?","support.titles.body":"Ivory Note analyse les sujets répétés dans toute la transcription et privilégie le thème dominant plutôt que les premières phrases.","support.contact":"Besoin d’aide ?","privacy.eyebrow":"Mentions légales Ivory Note","privacy.title":"Politique de confidentialité","privacy.lede":"Ivory Note est conçu pour garder vos notes vocales privées et sous votre contrôle.","privacy.date":"Date d’entrée en vigueur : 19 juin 2026"
        },
        de: {
            "nav.home":"Start","nav.support":"Support","nav.privacy":"Datenschutz","home.eyebrow":"Ivory Note 1.1","home.title":"Nimm Wichtiges auf. Behalte es für dich.","home.lede":"Ivory Note erkennt deine Sprache, erstellt ein klares Transkript und nützliches Lernmaterial, während deine Inhalte auf dem Gerät bleiben.","home.support":"Support erhalten","home.policy":"Datenschutzrichtlinie lesen","home.see":"Ivory Note ansehen","home.workspace":"Aufnehmen, transkribieren und lernen an einem ruhigen Ort.","home.caption.notes":"Organisierte Notizen","home.caption.record":"Aufnahme mit einem Tippen","home.caption.private":"Datenschutz von Anfang an","home.caption.watch":"Apple-Watch-Aufnahme","home.new":"Neu in 1.1","home.featuresTitle":"Deine Sprache. Der ganze Kontext. Weiterhin privat.","home.feature.transcription.title":"Mehrsprachige Transkription","home.feature.transcription.body":"Ivory Note erkennt automatisch die gesprochene Sprache und transkribiert lokal mit dem enthaltenen Modell.","home.feature.titles.title":"Kontextbezogene Titel","home.feature.titles.body":"Lange Aufnahmen werden nach dem Hauptthema benannt, nicht nach der Begrüßung oder den ersten Worten.","home.feature.languages.title":"Sieben App-Sprachen","home.feature.languages.body":"Nutze Ivory Note auf Englisch, Spanisch, Französisch, Deutsch, Portugiesisch, vereinfachtem Chinesisch oder Russisch.","home.privacy.eyebrow":"Datenschutz zuerst","home.privacy.title":"Kein Konto. Keine Werbung. Keine Cloud-Transkription.","home.privacy.body":"Notizen und Audio werden lokal gespeichert. Ivory Note betreibt weder Konten noch einen Server, der deine Aufnahmen empfängt. Du löschst Inhalte direkt in der App.","home.privacy.link":"Vollständige Richtlinie anzeigen","support.eyebrow":"Ivory Note Hilfe","support.lede":"Klare Hilfe zu Aufnahme, Transkription, Speicher, Widgets und Apple Watch.","support.languages.title":"Welche Sprachen unterstützt Ivory Note?","support.languages.body":"Ivory Note 1.1 erkennt die gesprochene Sprache automatisch während der Transkription auf dem Gerät. Die App ist auf Englisch, Spanisch, Französisch, Deutsch, Portugiesisch, vereinfachtem Chinesisch und Russisch verfügbar.","support.titles.title":"Wie benennt Ivory Note eine lange Aufnahme?","support.titles.body":"Ivory Note analysiert wiederkehrende Themen im gesamten Transkript und bevorzugt das Hauptthema statt der Begrüßung oder des ersten Satzes.","support.contact":"Noch Hilfe benötigt?","privacy.eyebrow":"Ivory Note Rechtliches","privacy.title":"Datenschutzrichtlinie","privacy.lede":"Ivory Note wurde entwickelt, damit deine Sprachnotizen privat und unter deiner Kontrolle bleiben.","privacy.date":"Gültig ab: 19. Juni 2026"
        },
        pt: {
            "nav.home":"Início","nav.support":"Suporte","nav.privacy":"Privacidade","home.eyebrow":"Ivory Note 1.1","home.title":"Grave o que importa. Mantenha-o seu.","home.lede":"O Ivory Note reconhece o idioma falado, cria uma transcrição clara e produz material de estudo útil, mantendo o conteúdo no dispositivo.","home.support":"Obter suporte","home.policy":"Ler a política de privacidade","home.see":"Conheça o Ivory Note","home.workspace":"Grave, transcreva e reveja num espaço tranquilo.","home.caption.notes":"Notas organizadas","home.caption.record":"Gravação com um toque","home.caption.private":"Privado desde a conceção","home.caption.watch":"Gravação no Apple Watch","home.new":"Novidades na versão 1.1","home.featuresTitle":"O seu idioma. Todo o contexto. Sempre privado.","home.feature.transcription.title":"Transcrição multilingue","home.feature.transcription.body":"O Ivory Note deteta automaticamente o idioma falado e transcreve localmente com o modelo incluído.","home.feature.titles.title":"Títulos com contexto","home.feature.titles.body":"As gravações longas recebem títulos com base no tema principal, não na saudação ou nas primeiras palavras.","home.feature.languages.title":"Sete idiomas de interface","home.feature.languages.body":"Use o Ivory Note em inglês, espanhol, francês, alemão, português, chinês simplificado ou russo.","home.privacy.eyebrow":"Privacidade primeiro","home.privacy.title":"Sem conta. Sem anúncios. Sem transcrição na nuvem.","home.privacy.body":"As notas e os áudios são guardados localmente. O Ivory Note não utiliza contas nem um servidor que receba as gravações. O utilizador controla a eliminação na app.","home.privacy.link":"Ver a política completa","support.eyebrow":"Ajuda do Ivory Note","support.lede":"Ajuda clara para gravação, transcrição, armazenamento, widgets e Apple Watch.","support.languages.title":"Que idiomas são suportados pelo Ivory Note?","support.languages.body":"O Ivory Note 1.1 deteta automaticamente o idioma falado durante a transcrição no dispositivo. A interface está disponível em inglês, espanhol, francês, alemão, português, chinês simplificado e russo.","support.titles.title":"Como é criado o título de uma gravação longa?","support.titles.body":"O Ivory Note analisa temas repetidos em toda a transcrição e dá prioridade ao tópico dominante em vez da saudação ou primeira frase.","support.contact":"Ainda precisa de ajuda?","privacy.eyebrow":"Informação legal do Ivory Note","privacy.title":"Política de Privacidade","privacy.lede":"O Ivory Note foi concebido para manter as notas de voz privadas e sob o seu controlo.","privacy.date":"Data de entrada em vigor: 19 de junho de 2026"
        },
        "zh-Hans": {
            "nav.home":"首页","nav.support":"支持","nav.privacy":"隐私","home.eyebrow":"Ivory Note 1.1","home.title":"记录重要内容，始终由你掌控。","home.lede":"Ivory Note 可识别你所说的语言，生成清晰的转写和实用学习材料，同时将内容保留在设备上。","home.support":"获取支持","home.policy":"阅读隐私政策","home.see":"了解 Ivory Note","home.workspace":"在安静简洁的空间中录音、转写和复习。","home.caption.notes":"整齐的笔记","home.caption.record":"一键录音","home.caption.private":"隐私内建","home.caption.watch":"Apple Watch 录音","home.new":"1.1 新功能","home.featuresTitle":"你的语言。完整语境。依然私密。","home.feature.transcription.title":"多语言转写","home.feature.transcription.body":"Ivory Note 自动检测口语语言，并使用内置语音模型在本地完成转写。","home.feature.titles.title":"基于语境的标题","home.feature.titles.body":"长录音会根据主要主题生成标题，而不是使用问候语或开头几个词。","home.feature.languages.title":"七种界面语言","home.feature.languages.body":"Ivory Note 支持英语、西班牙语、法语、德语、葡萄牙语、简体中文和俄语界面。","home.privacy.eyebrow":"隐私优先","home.privacy.title":"无需账户。没有广告。不使用云端转写。","home.privacy.body":"你的笔记和音频存储在本地。Ivory Note 不提供账户系统，也没有接收录音的服务器。你可以在应用内自行删除内容。","home.privacy.link":"查看完整政策","support.eyebrow":"Ivory Note 帮助","support.lede":"有关录音、转写、存储、小组件和 Apple Watch 的清晰帮助。","support.languages.title":"Ivory Note 支持哪些语言？","support.languages.body":"Ivory Note 1.1 会在设备端转写时自动检测口语语言。应用界面支持英语、西班牙语、法语、德语、葡萄牙语、简体中文和俄语。","support.titles.title":"Ivory Note 如何为长录音生成标题？","support.titles.body":"Ivory Note 会分析完整转写中反复出现的主题，优先使用主要话题，而不是问候语或第一句话。","support.contact":"仍需帮助？","privacy.eyebrow":"Ivory Note 法律信息","privacy.title":"隐私政策","privacy.lede":"Ivory Note 旨在让你的语音笔记保持私密并始终由你掌控。","privacy.date":"生效日期：2026 年 6 月 19 日"
        },
        ru: {
            "nav.home":"Главная","nav.support":"Поддержка","nav.privacy":"Конфиденциальность","home.eyebrow":"Ivory Note 1.1","home.title":"Записывайте важное. Оставляйте это своим.","home.lede":"Ivory Note распознаёт язык речи, создаёт точную расшифровку и полезные учебные материалы, сохраняя содержимое на устройстве.","home.support":"Получить помощь","home.policy":"Прочитать политику конфиденциальности","home.see":"Посмотрите Ivory Note","home.workspace":"Записывайте, расшифровывайте и повторяйте в спокойном рабочем пространстве.","home.caption.notes":"Организованные заметки","home.caption.record":"Запись одним касанием","home.caption.private":"Конфиденциальность по умолчанию","home.caption.watch":"Запись с Apple Watch","home.new":"Новое в версии 1.1","home.featuresTitle":"Ваш язык. Полный контекст. Полная конфиденциальность.","home.feature.transcription.title":"Многоязычная расшифровка","home.feature.transcription.body":"Ivory Note автоматически определяет язык речи и расшифровывает её локально с помощью встроенной модели.","home.feature.titles.title":"Названия с учётом контекста","home.feature.titles.body":"Длинные записи получают название по основной теме, а не по приветствию или первым словам.","home.feature.languages.title":"Семь языков интерфейса","home.feature.languages.body":"Используйте Ivory Note на английском, испанском, французском, немецком, португальском, упрощённом китайском или русском языке.","home.privacy.eyebrow":"Конфиденциальность прежде всего","home.privacy.title":"Без аккаунта. Без рекламы. Без облачной расшифровки.","home.privacy.body":"Заметки и аудио хранятся локально. У Ivory Note нет системы аккаунтов или сервера, получающего ваши записи. Вы удаляете данные непосредственно в приложении.","home.privacy.link":"Открыть полную политику","support.eyebrow":"Помощь Ivory Note","support.lede":"Понятная помощь по записи, расшифровке, хранилищу, виджетам и Apple Watch.","support.languages.title":"Какие языки поддерживает Ivory Note?","support.languages.body":"Ivory Note 1.1 автоматически определяет язык речи при расшифровке на устройстве. Интерфейс доступен на английском, испанском, французском, немецком, португальском, упрощённом китайском и русском языках.","support.titles.title":"Как Ivory Note называет длинную запись?","support.titles.body":"Ivory Note анализирует повторяющиеся темы во всей расшифровке и выбирает главную тему вместо приветствия или первого предложения.","support.contact":"Нужна помощь?","privacy.eyebrow":"Правовая информация Ivory Note","privacy.title":"Политика конфиденциальности","privacy.lede":"Ivory Note помогает сохранять голосовые заметки конфиденциальными и под вашим контролем.","privacy.date":"Дата вступления в силу: 19 июня 2026 г."
        }
    };

    const normalize = (value) => {
        if (!value) return "en";
        const lower = value.toLowerCase();
        if (lower.startsWith("zh")) return "zh-Hans";
        const short = lower.split("-")[0];
        return translations[short] ? short : "en";
    };

    const params = new URLSearchParams(window.location.search);
    const requested = params.get("lang") || localStorage.getItem("ivory-language") || navigator.language;
    const language = normalize(requested);
    const strings = translations[language] || english;

    document.documentElement.lang = language;
    document.querySelectorAll("[data-i18n]").forEach((element) => {
        const key = element.dataset.i18n;
        element.textContent = strings[key] || english[key] || element.textContent;
    });
    document.querySelectorAll("[data-language-picker]").forEach((picker) => {
        picker.value = language;
        picker.addEventListener("change", () => {
            localStorage.setItem("ivory-language", picker.value);
            const url = new URL(window.location.href);
            url.searchParams.set("lang", picker.value);
            window.location.assign(url.toString());
        });
    });
})();
